application: artcaillautest
version: 1
runtime: python27
api_version: 1
threadsafe: true

builtins:
- deferred: on

libraries:
- name: django
  version: "1.4"

inbound_services:
- warmup

handlers:

- url: /static
  static_dir: static
  expiration: '1m'

- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico

- url: /appengine_sessions/clean-up/
  script: main.app
  login: admin

- url: /.*
  script: main.app

skip_files:
- ^(.*/)?app.yaml
- ^(.*/)?app.yml
- ^(.*/)?index.yaml
- ^(.*/)?index.yml
- ^(.*/)?.*\.py[co]
- ^(.*/)?\..*
- tmp
